[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = { version = "2.13.0", features = ["chrono-0_4"] }
chrono = "0.4.38"
mongodb = "3.1.0"
serde = "1.0.210"
tokio = "1.40.0"
