---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec:
  volumes:
  - name: mongo-storage
    hostPath:
      path: /mnt/c/Users/abvan/Documents/GitHub/relic-backend/data/mongo/backup
      type: Directory
  containers:
  - name: db
    image: mongo:latest
    volumeMounts:
    - name: mongo-storage
      mountPath: /data/backup
    ports:
    - containerPort: 27017
      hostPort: 27017
    resources:
      limits:
        cpu: 1
        memory: 512Mi
